import sys
from collections import deque
n=int(sys.stdin.readline())
s=deque()
for i in range(n):
    l=list(map(str,sys.stdin.readline().split()))
    m=len(s)
    if(l[0]=='push_front'):
        a=int(l[1])
        s.appendleft(a)
    if(l[0]=='push_back'):
        a=int(l[1])
        s.append(a)
    elif(l[0]=='pop_front'):
        if(m==0):
            print(-1)
        else:
            a=s.popleft()
            print(a)
    elif(l[0]=='pop_back'):
        if(m==0):
            print(-1)
        else:
            a=s.pop()
            print(a)
    elif(l[0]=='front'):
        if(m==0):
            print(-1)
        else:
            print(s[0])
    elif(l[0]=='back'):
        if(m==0):
            print(-1)
        else:
            print(s[m-1])
    elif(l[0]=='size'):
        print(m)
    elif(l[0]=='empty'):
        if(m==0):
            print(1)
        else:
            print(0)