-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE * OS.SALES SALES
FROM PRODUCT P 
    JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES
        FROM OFFLINE_SALE
         GROUP BY PRODUCT_ID) OS
    ON P.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE