-- 코드를 입력하세요
SELECT CAR_ID, CAR.CAR_TYPE, CAST((DAILY_FEE* 30 *(1-DISCOUNT_RATE/100)) AS UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN(SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
                                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                    WHERE DURATION_TYPE = '30일 이상')AS PLAN
                                    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE (CAR.CAR_TYPE= 'SUV' OR CAR.CAR_TYPE= '세단')
AND NOT EXISTS (SELECT 1
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                WHERE CAR.CAR_ID = HISTORY.CAR_ID
                AND HISTORY.START_DATE < '2022-12-01'
                AND (HISTORY.END_DATE) >'2022-11-01')
AND (DAILY_FEE* 30 *(1-DISCOUNT_RATE/100) >=500000
     AND DAILY_FEE* 30 *(1-DISCOUNT_RATE/100)<2000000)
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC