-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI JOIN
    (SELECT FOOD_TYPE, MAX(FAVORITES) MAX_F
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS MAX_R
    ON RI.FOOD_TYPE = MAX_R.FOOD_TYPE 
    AND RI.FAVORITES = MAX_R.MAX_F
ORDER BY FOOD_TYPE DESC