/*
ANIMAL_INS
ANIMAL_OUTS
===============================
입양을 못 간 동물 중 가장 오래 보호소에 있었던 동물 3마리: WHRE 입양x, ORDER BY DATETIME LIMIT 3

SELECT NAME, DATETIME
ORDER BY DATETIME(보호 시작일)
*/
SELECT A.NAME, A.DATETIME
  FROM ANIMAL_INS AS A
  LEFT JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC
LIMIT 3