-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT AS FP
    JOIN FOOD_ORDER AS FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE MONTH(FO.PRODUCE_DATE) = 5
AND YEAR(FO.PRODUCE_DATE)= 2022
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC