-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF FH
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
        FROM JULY
        GROUP BY FLAVOR
    ) J
    ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.JULY_TOTAL DESC
LIMIT 3