/*
ANIMAL_INS 

ANIMAL_OUTS ANIMAL_ID
==========================
보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회
SELECT ANIMAL_ID NAME
ORDER BY 보호 시작일

*/

-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
  FROM ANIMAL_INS AS A
  JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID  = B.ANIMAL_ID
 WHERE A.DATETIME > B.DATETIME
 ORDER BY A.DATETIME